export const LOGIN_USER_REQUEST="LOGIN_USER_REQUEST"
export const LOGIN_USER_SUCCESS="LOGIN_USER_SUCCESS"
export const LOGIN_USER_FAILURE="LOGIN_USER_FAILURE"

export const REGISTER_USER_REQUEST="REGISTER_USER_REQUEST"
export const REGISTER_USER_SUCCESS="REGISTER_USER_SUCCESS"
export const REGISTER_USER_FAILURE="REGISTER_USER_FAILURE"

export const GET_USER_PROFILE_REQUEST="GET_USER_PROFILE_REQUEST"
export const GET_USER_PROFILE_SUCCESS="GET_USER_PROFILE_SUCCESS"
export const GET_USER_PROFILE_FAILURE="GET_USER_PROFILE_FAILURE"

export const UPDATE_USER_REQUEST="UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE="UPDATE_USER_FAILURE"

export const SEARCH_USER_REQUEST="SEARCH_USER_REQUEST"
export const SEARCH_USER_SUCCESS="SEARCH_USER_SUCCESS"
export const SEARCH_USER_FAILURE="SEARCH_USER_FAILURE"

export const FIND_USER_BY_ID_REQUEST="FIND_USER_BY_ID_REQUEST"
export const FIND_USER_BY_ID_SUCCESS="FIND_USER_BY_ID_SUCCESS"
export const FIND_USER_BY_ID_FAILURE="FIND_USER_BY_ID_FAILURE"

export const FOLLOW_USER_REQUEST="FOLLOW_USER_REQUEST"
export const FOLLOW_USER_SUCCESS="FOLLOW_USER_SUCCESS"
export const FOLLOW_USER_FAILURE="FOLLOW_USER_FAILURE"

export const LOGOUT="LOGOUT"

export const TWEET_CREATE_REQUEST="TWEET_CREATE_REQUEST"
export const TWEET_CREATE_SUCCESS="TWEET_CREATE_SUCCESS"
export const TWEET_CREATE_FAILURE="TWEET_CREATE_FAILURE"

export const TWEET_DELETE_REQUEST="TWEET_DELETE_REQUEST"
export const TWEET_DELETE_SUCCESS="TWEET_DELETE_SUCCESS"
export const TWEET_DELETE_FAILURE="TWEET_DELETE_FAILURE"

export const GET_ALL_TWEETS_REQUEST="GET_ALL_TWEETS_REQUEST"
export const GET_ALL_TWEETS_SUCCESS="GET_ALL_TWEETS_SUCCESS"
export const GET_ALL_TWEETS_FAILURE="GET_ALL_TWEETS_FAILURE"

export const GET_USERS_TWEET_REQUEST="GET_USERS_TWEET_REQUEST"
export const GET_USERS_TWEET_SUCCESS="GET_USERS_TWEET_SUCCESS"
export const GET_USERS_TWEET_FAILURE="GET_USERS_TWEET_FAILURE"

export const USER_LIKE_TWEET_REQUEST="USER_LIKE_TWEET_REQUEST"
export const USER_LIKE_TWEET_SUCCESS="USER_LIKE_TWEET_SUCCESS"
export const USER_LIKE_TWEET_FAILURE="USER_LIKE_TWEET_FAILURE"

export const FIND_TWEET_BY_ID_REQUEST="FIND_TWEET_BY_ID_REQUEST"
export const FIND_TWEET_BY_ID_SUCCESS="FIND_TWEET_BY_ID_SUCCESS"
export const FIND_TWEET_BY_ID_FAILURE="FIND_TWEET_BY_ID_FAILURE"

export const REPLY_TWEET_REQUEST="REPLY_TWEET_REQUEST"
export const REPLY_TWEET_SUCCESS="REPLY_TWEET_SUCCESS"
export const REPLY_TWEET_FAILURE="REPLY_TWEET_FAILURE"

export const RETWEET_REQUEST="RETWEET_REQUEST"
export const RETWEET_SUCCESS="RETWEET_SUCCESS"
export const RETWEET_FAILURE="RETWEET_FAILURE"

export const LIKE_TWEET_REQUEST="LIKE_TWEET_REQUEST"
export const LIKE_TWEET_SUCCESS="LIKE_TWEET_SUCCESS"
export const LIKE_TWEET_FAILURE="LIKE_TWEET_FAILURE"

